### ISSUE TITLE
Crashes if one of the Images is missing

### ISSUE THREAD

**Issue by milifilou** [SamuelMiddendorp/pokemonTCG-image-downloader#1]
As described in the Read Me file, I tried to download all of the images. During that, I noticed that one of my sets was much smaller than it was supposed to be. HSP only downloaded 17 files before getting a very verbose crash. Looking into pokemonTCG db, i saw that card 18 had no image available, but the later images in that set are available. While this is extremely low priority, would it be possible to add 404 handling to this script? It would be nice for it to write a line to console about the card not being available, and then continuing with the other cards. 
Thank you very much for publishing this script, since I struggled hard trying to write one myself

**Comment by SamuelMiddendorp** [comment]
Hi Milifilou,

Thank you for your request, I have just implemented a change that should fix the issue, I have tested it and it seems to be working but do let me know if it works on your end so we can close this issue!

**Comment by milifilou** [comment]
Can confirm this fixes it on my end as well!
